apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mlops
  name: backend
spec:
  ports:
  - port: 5960
    protocol: TCP
    targetPort: 5960
    nodePort: 30007
  selector:
    name: mlops
  type: NodePort
status:
  loadBalancer: {}
