apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: mlops
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: mlops
spec:
  hostname: backend
  subdomain: default-subdomain
  containers:
  - image: kartikar09/mlops_helm:latest
    name: backend
    ports:
    - containerPort: 5960
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: mlops
spec:
  hostname: frontend
  subdomain: default-subdomain
  containers:
  - image: kartikar09/mlops_frontend:latest
    name: frontend
    ports:
    - containerPort: 80
